services:
  mysql:
    image: mysql:8.0
    container_name: container_mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: appschool
      MYSQL_USER: user
      MYSQL_PASSWORD: password
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: container_phpmyadmin
    restart: always
    environment:
      PMA_HOST: mysql
      MYSQL_ROOT_PASSWORD: password
    ports:
      - "5051:80"
    depends_on:
      - mysql

  php:
    build:
      context: ./php
      dockerfile: Dockerfile
    container_name: appschool_container_php
    restart: always
    volumes:
      - ./project:/var/www/html/
    ports:
      - "8080:80"
    depends_on:
      - mysql

volumes:
  mysql_data: